# Utiliza una imagen de Maven como contenedor intermedio para compilar el proyecto
FROM maven:3.8.1-jdk-11 AS build
WORKDIR /CajeroNeoris
COPY src /CajeroNeoris/src
COPY pom.xml /CajeroNeoris


# Utiliza una imagen de OpenJDK para ejecutar el binario (.jar)
FROM openjdk:11-jre-slim
run dir
COPY --from=build /target/CajeroNeoris.jar /CajeroNeoris.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/CajeroNeoris.jar"]